# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/EarlyDarkEmu',
                'doc_host': 'https://nesar.github.io',
                'git_url': 'https://github.com/nesar/EarlyDarkEmu',
                'lib_path': 'EarlyDarkEmu'},
  'syms': {'EarlyDarkEmu.core': {'EarlyDarkEmu.core.foo': ('core.html#foo', 'EarlyDarkEmu/core.py')}}}
