# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_pca.ipynb.

# %% auto 0
__all__ = ['do_pca']

# %% ../nbs/01_pca.ipynb 3
from sepia.SepiaModel import SepiaModel
from sepia.SepiaData import SepiaData

# %% ../nbs/01_pca.ipynb 4
def do_pca(sepia_data:SepiaData=None, # Input data in SEPIA format
           exp_variance:float=0.98, # Explained variance
           do_discrepancy:bool=False, #For discrepancy modeling
          ) -> SepiaModel: # sepia.SepiaModel.SepiaModel
    
    # Transform
    sepia_data.transform_xt()
    sepia_data.standardize_y()
    # Compute basis
    sepia_data.create_K_basis(n_pc=exp_variance)        # Explain 95% of variance
    if do_discrepancy:
        sepia_data.create_D_basis()
    # Set up the model
    sepia_model = SepiaModel(sepia_data)
    
    return sepia_model
